### ISSUE TITLE
Make this a Swift Package

### ISSUE THREAD

**Issue by KyNorthstar** [George-J-E/HidingViews#3]
This would make an awesome micro-package! Would love to actually use it as one in my projects rather than just copying the code into them manually

**Comment by GeorgeElsham** [comment]
I'll be honest, I don't know how to do that, and I don't know whether it is worth it. But feel free though to do that, and you can make a clone and all that stuff and I will accept the pull request. :)

**Comment by KyNorthstar** [comment]
Gotcha! #4
