### ISSUE TITLE
Create 1.0.0 release

### ISSUE THREAD

**Issue by KyNorthstar** [George-J-E/HidingViews#5]
Although the file structure is there to make this a Swift Package, [one more requirement](https://swift.org/package-manager/#importing-dependencies) is that there is a release whose tag is [a semantic version](https://SemVer.org). Creating a 1.0.0 release will accomplish this.

Do note that the tag must be only a semantic version, so `1.0.0` will work, but `v1.0.0` will not.

**Comment by GeorgeElsham** [comment]
How is this done? Do I just need to change the version from `1.0` to `1.0.0` in the project settings / `info.plist`?

**Comment by KyNorthstar** [comment]
This is a part of Git, so no file changes are necessary. In GitHub, you can go to [the releases page](https://github.com/BenLeggiero/Swift-Version-Checker/releases) and [create a new release](https://github.com/George-J-E/HidingViews/releases/new). Then, put `1.0.0` in the "Tag version" field, and make sure you've selected the `master` branch.

However, if you don't want to use GitHub releases, simply use any Git client to push a `1.0.0` tag at the top of the `master` branch; that's all Swift Package Manager looks for.

**Comment by GeorgeElsham** [comment]
Ok thank you! Now updated :)
